version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - aws --version
artifacts:
  files:
    - target/PointsMicroservice-0.0.1-SNAPSHOT.jar
